### ISSUE TITLE
place a sample .proxyswitch.rc file?

### ISSUE THREAD

**Issue by ottomao** [lululau/proxy-switcher-alfred-workflow#3]
Hi,
Would you please put a sample for .proxyswitch.rc ? Otherwise, I have no idea about configing my preference.
Thx !

**Comment by lululau** [comment]
Hi @ottomao,
Contents of `.proxyswitcher.rc` are lines of network service names, for example, if you wanna only show options for Wi-Fi，you can generate the `.proxyswitcher.rc` file by executing this command: `echo Wi-Fi > ~/.proxyswitcher.rc`.  You could get names of all available network services by this command:  `networksetup -listallnetworkservices`

**Comment by ottomao** [comment]
So they are nothing but service names ? What if I want to save some config (e.g. pac file address) persistently ?

**Comment by lululau** [comment]
@ottomao Sorry, the extension has no feature about saving service config, they are just service names in the `.rc` file.

**Comment by ottomao** [comment]
Okay , got it.
Thank you!
