### ISSUE TITLE
切换代理的时候需要密码

### ISSUE THREAD

**Issue by ionull** [lululau/proxy-switcher-alfred-workflow#5]
只是随口问下，平时我们通过WIFI设置里更改代理好像不需要输入密码的，也没那个锁的图标。这个能解决吗？实在太烦人了。

**Comment by jostyee** [comment]
可以保存到keychain吧

**Comment by ionull** [comment]
是系统用户的密码呀……就是类似需要sudo权限那个密码……

**Comment by lululau** [comment]
@ionull 
对不起，我没找到可以让 networksetup 命令不需要输入口令就可以执行破坏性操作的方法，有一个办法，是需要你自己修改：在 sudo file 里设置执行 networksetup 不需要口令，并且需要把这个 workflow 中的脚本中的

```
if [[ ! -z "{query}" ]]
then
{query}
fi
```

 修改为

```
if [[ ! -z "{query}" ]]
then
sudo {query}
fi
```

**Comment by jostyee** [comment]
https://www.dimitrikoenig.net/better-usage-of-sensible-user-data-for-alfred-workflows.html

**Comment by ionull** [comment]
@lululau 很感谢，我是想到goagent-x貌似就不用输入密码自动切换代理，所以也不知道是不是alfred限制所以你们这边没法处理，等我有空了再来好好研究下。非常感谢。

**Comment by cottonty** [comment]
直接写sudo {query} 好像没法执行

可以把脚本里的{query}改成
echo "你的密码"|sudo -S {query}

如果你不介意明文就这么把密码写出来的话……

**Comment by tufu9441** [comment]
@cottonty 是的，我就是按照你说的这么用的😂
